### ISSUE TITLE
A `Maybe` field will be invalid against a `null`

### ISSUE THREAD

**Issue by parsonsmatt** [GetShopTV/swagger2#142]
I'm getting validation errors against `Maybe` fields:

```haskell
>>> :set -XDeriveGeneric
>>> data X = X { foo :: Maybe Int } deriving (Show, Generic)
>>> instance ToSchema X
>>> instance ToJSON X
>>> validateToJSON (X Nothing)
["expected JSON value of type SwaggerInteger"]
>>> encode (X Nothing)
"{\"foo\":null}"
```

Omitting `"foo"` from the `required` fields does not fix this issue.

What's the right way to get maybe fields to validate correctly?

**Comment by fizruk** [comment]
I personally use `omitNothingFields` for all my JSON instances, so I don't encounter this problem.

We could alter `validateToJSON` so that `null` is considered equivalent to a missing field.
Although I'm not 100% sure that's the right thing to do (I think it might break some code in theory).

A better solution would probably be to add some `nullable` support (e.g. see #128).

**Comment by fizruk** [comment]
Ah, I see `omitNothingFields` actually has nothing to do with your problem.

Your problem is because of a weird behaviour feature (bug) of Generic-based `ToSchema` instance which only happens for **single field data types with `Maybe`**! It just so happens that I've never tried that case.

This is how everything works if you just add another field (even without `omitNothingFields`):

```haskell
>>> data X = X { foo :: Maybe Int, bar :: Maybe String } deriving (Show, Eq, Generic)
>>> instance ToJSON X
>>> instance ToSchema X
>>> validateToJSON (X Nothing Nothing)
[]
```

### What's causing this

The problem is specifically due to [this line](https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L739):

```haskell
      recordSchema = gdeclareNamedSchema opts (Proxy :: Proxy (S1 s f)) s
```

Which calls something with `S1 s f` and then GHC just picks [this instance](https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L790-L792):

```haskell
instance OVERLAPPABLE_ (Selector s, GToSchema f) => GToSchema (S1 s f) where ...
```

over [this one](https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L786-L788):

```haskell
instance OVERLAPPING_ (Selector s, ToSchema c) => GToSchema (S1 s (K1 i (Maybe c))) where ...
```

even when there's a `Maybe`. That's because GHC has to pick an instance before it knows whether it can specialise to `Maybe` or not.

I think I'm going to send a PR fixing this right now.
