### ISSUE TITLE
ToSchema, proxy, and GeneralizedNewtypeDeriving

### ISSUE THREAD

**Issue by michalrus** [GetShopTV/swagger2#150]
This won’t work:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

newtype SomeId =
  SomeId UUID
  deriving (Show, Eq, Ord, ToJSON, FromJSON, ToJSONKey, FromJSONKey, ToSchema, ToField, FromField)
```

with the following error:

```
    • Couldn't match representation of type ‘proxy UUID’
                               with that of ‘proxy SomeId’
        arising from the coercion of the method ‘Data.Swagger.Internal.Schema.declareNamedSchema’
          from type ‘forall (proxy :: * -> *).
                     proxy UUID
                     -> Data.Swagger.Declare.Declare
                          (Data.Swagger.Internal.Definitions Data.Swagger.Internal.Schema)
                          Data.Swagger.Internal.NamedSchema’
            to type ‘forall (proxy :: * -> *).
                     proxy SomeId
                     -> Data.Swagger.Declare.Declare
                          (Data.Swagger.Internal.Definitions Data.Swagger.Internal.Schema)
                          Data.Swagger.Internal.NamedSchema’
      NB: We cannot know what roles the parameters to ‘proxy’ have;
        we must assume that the role is nominal
    • When deriving the instance for (ToSchema SomeId)
   |
44 |   deriving (Show, Eq, Ord, ToJSON, FromJSON, ToJSONKey, FromJSONKey, ToSchema, ToField, FromField)
   |                                                                      ^^^^^^^^
```

Perhaps when using a concrete `Data.Proxy.Proxy` instead of `forall proxy. proxy`, this would’ve worked?

**Comment by phadej** [comment]
Alternatively we could have `TaggedNamedSchema a`. which might be even better..

**Comment by phadej** [comment]
@michalrus note that *GND* is questionable for `ToSchema` though, as the name of the schema won't change, it will be still `UUID`. It might be what you want, or not.

**Comment by michalrus** [comment]
Ohhhhhh, right, absolutely! I don’t want that. Sorry for the noise!

**Comment by fieldstrength** [comment]
Hi! I recently found myself affected by this design decision as well. I would be quite interested if there is some way to have a workaround. If so I'd be willing to help with the implementation.

My use case involves `DerivingVia`. I have a newtype that keeps track of how to transform the JSON encodings. This is quite valuable to us because it prevents the various type classes that know about the encoding from getting out of sync. 

```haskell 
data MyRecord = MyRecord 
  { ...
  } deriving stock Generic
    deriving (FromJSON, ToJSON, Flow, ToSchema) via APIEncoding SnakeCase MyRecord
```

This is what I want to write (see [here](https://gist.github.com/fieldstrength/b83cf70c4b819e9abf00c560bd960202) for a gist). Everything works beautifully until we get to `ToSchema` for the reason mentioned in this issue: the type parameter role is assumed to be nominal.

Now about the solution: 

@phadej It sounds like you had an idea, but it is not immediately clear to me what it is. Maybe you could illuminate? Something involved the `Tagged` type?

I suspect there would be compatibility concerns around simply changing the function signature to take a concrete `Proxy` (is anyone using the fact that its polymorphic?) so I suppose we could add a new method with this signature, and require that either one be specified. Admittedly it does seem a bit unfortunate to pollute the class in this way though.

Is there a better way?

**Comment by phadej** [comment]
Adding new method won't help GND/DerivingVia. All methods have to be coercible

**Comment by fizruk** [comment]
@fieldstrength I know this is not as neat as `DerivingVia`, but you can always do this:

```haskell
instance ToSchema Example where
  declareNamedSchema _ = declareNamedSchema (Proxy @ (APIEncoding SnakeCaseDropPrefix Example))
```

See the [full gist](https://gist.github.com/fizruk/c2a5e5fd3310b915b5b124e511096919) (based on yours).

@phadej how much code would we break if we switch from `proxy` to `Proxy`? I don't really see the benefit of `proxy` anymore, do you?

**Comment by fieldstrength** [comment]
Thanks for the feedback and pointers!

I was encouraged @fizruk that you seem positive towards the change so I went ahead and made the PR. Happily, it is a quite small patch. I have also sanity-checked that it does indeed allow `DerivingVia` to work.
