### ISSUE TITLE
Make Day date format explicit

### ISSUE THREAD

**Issue by agrafix** [GetShopTV/swagger2#73]
```haskell
-- | Format @"date"@ corresponds to @yyyy-mm-dd@ format.
instance ToParamSchema Day where
  toParamSchema _ = timeParamSchema "date"
```

Is there a reason why this is not explicitly `toParamSchema _ = timeParamSchema "yyyy-mm-dd"`?

**Comment by fizruk** [comment]
Yes, `date` is one of the officially supported formats and is treated somewhat specially by Swagger UI. Specifically, it automatically gains valid example and its "Data Type" appears as "date" rather than "string". In the future Swagger UI might also add date picker, although it is not currently implemented.

![screen shot 2016-08-12 at 23 58 22](https://cloud.githubusercontent.com/assets/686582/17633841/3a7c83a4-60f1-11e6-93f9-8af20c0b6c64.png)

**Comment by agrafix** [comment]
Cool thanks for the quick reply! :-)
